### PR TITLE
Various tweaks/nerfs

### PR DESCRIPTION
**Pull request by heinermann**
- Nerfed TNT thrower in the mines (regular version in coal pits is still buffed).
- Flying fish now have a random activation timer and don't fly out of the pool immediately.
- Halve chance of replacing text with butt.
- Corrupted enemy spawns scale up depending on biome.
- All but last HM transforms materials through the pixel scene instead of a material converter entity.
- Slightly reduce chance of replacing text with a random language.
- Make rain less bullshit.
- Rain now has cloudcover & better ui support.
- Fix an error with fairmod_metal_rust.
- Add an explanation as to why killing flying fish summons Steve since it's unclear (through a letter).

### CODE REVIEW

**Comment by NathanSnail** [comment]
maybe remove the anger gods fish? im not sure anyone likes it

**Comment by NathanSnail** [comment]
Also whats wrong with rain?

**Comment by heinermann** [comment]
> Also whats wrong with rain?

It's mainly that it just instantly explodes everywhere and you die, while also being too common. IIRC people were talking about adding more surface things and players will just avoid the surface entirely if there's a 1/30 chance of instant death every time it rains or whatever. I find a lot of the "you instantly explode for no reason" stuff is just not very funny and turns people away, and I think if it's going to do it there should either be some sort of lead up or consistent interaction.

> maybe remove the anger gods fish? im not sure anyone likes it

Let me find out and ask whoever added it.

**Comment by dextercd** [comment]
>Slightly reduce chance of replacing text with a random language.

That's langmix not translation_shuffle.

**Comment by heinermann** [comment]
> > Slightly reduce chance of replacing text with a random language.
> 
> That's langmix not translation_shuffle.

Oops, will have follow up

**Pull request merged**
